/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_androidndk_Hello */

#ifndef _Included_com_example_administrator_androidndk_Hello
#define _Included_com_example_administrator_androidndk_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_androidndk_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_androidndk_Hello_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_example_administrator_androidndk_Hello
 * Method:    sayHowOld
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_androidndk_Hello_sayHowOld
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_administrator_androidndk_Hello
 * Method:    sayLikeChengDu
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_androidndk_Hello_sayLikeChengDu
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_administrator_androidndk_Hello
 * Method:    sayComeFromShuangLiu
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_androidndk_Hello_sayComeFromShuangLiu
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
